USE [master]
GO

/****** Object:  Database [shoppingListTest]    Script Date: 29.7.2020. 23:22:11 ******/
CREATE DATABASE [shoppingListTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'shoppingListTest', FILENAME = N'C:\Users\KristijanPC\shoppingListTest.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'shoppingListTest_log', FILENAME = N'C:\Users\KristijanPC\shoppingListTest_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [shoppingListTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [shoppingListTest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [shoppingListTest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [shoppingListTest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [shoppingListTest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [shoppingListTest] SET ARITHABORT OFF 
GO

ALTER DATABASE [shoppingListTest] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [shoppingListTest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [shoppingListTest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [shoppingListTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [shoppingListTest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [shoppingListTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [shoppingListTest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [shoppingListTest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [shoppingListTest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [shoppingListTest] SET  ENABLE_BROKER 
GO

ALTER DATABASE [shoppingListTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [shoppingListTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [shoppingListTest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [shoppingListTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [shoppingListTest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [shoppingListTest] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [shoppingListTest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [shoppingListTest] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [shoppingListTest] SET  MULTI_USER 
GO

ALTER DATABASE [shoppingListTest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [shoppingListTest] SET DB_CHAINING OFF 
GO

ALTER DATABASE [shoppingListTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [shoppingListTest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [shoppingListTest] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [shoppingListTest] SET QUERY_STORE = OFF
GO

USE [shoppingListTest]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [shoppingListTest] SET  READ_WRITE 
GO

